/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Modelo.Cliente;
import Modelo.Habitacion;
import java.awt.BorderLayout;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author usuario
 */
public class PaginaPrincipal extends javax.swing.JFrame {
    PnlCliente pnlCliente;
    PnlServicios2 pnlServicios2;
    PnlPrincipal pnlPrincipal;    
    //PnlHabitacion21 pnlHabitacion21;
    PnlHabitacion21 pnlHabitacion21;
    PnlServicios pnlServicios;
    public static ArrayList<Habitacion> listaDeHabitaciones;
    public static ArrayList<Cliente> listaDeClientes;
    /**
     * Creates new form PaginaPrincipal
     */

    public PaginaPrincipal() {
        initComponents();
        setLocationRelativeTo(this);
        pnlPrincipal=new PnlPrincipal();
        agregarPanel(pnlPrincipal);
        fecha();
      
        listaDeClientes = new ArrayList<>();
        listaDeHabitaciones = new ArrayList<>();
        listaDeHabitaciones.add(new Habitacion("Matrominial",2,25,2,80));
        listaDeHabitaciones.add(new Habitacion("Matrimonial",2,20,2,80));
        listaDeHabitaciones.add(new Habitacion("Matrimonial",2,28,2,80));
        listaDeHabitaciones.add(new Habitacion("Simple",2,30,2,80));
        listaDeHabitaciones.add(new Habitacion("Simple",2,30,2,80));
        listaDeHabitaciones.add(new Habitacion("Simple",2,30,2,80));
        
        listaDeHabitaciones.add(new Habitacion("Triple",2,30,2,80));
        listaDeHabitaciones.add(new Habitacion("Triple",2,30,2,80));
        listaDeHabitaciones.add(new Habitacion("Triple",2,30,2,80));
        
        listaDeHabitaciones.add(new Habitacion("Cuadruple",2,30,2,80));
        listaDeHabitaciones.add(new Habitacion("Cuadruple",2,30,2,80));
        listaDeHabitaciones.add(new Habitacion("Cuadruple",2,30,2,80));
        
        listaDeHabitaciones.add(new Habitacion("ConnectingRooms",2,30,2,80));
        listaDeHabitaciones.add(new Habitacion("ConnectingRooms",2,30,2,80));
        listaDeHabitaciones.add(new Habitacion("ConnectingRooms",2,30,2,80));
        
        listaDeHabitaciones.add(new Habitacion("Suite",2,30,2,80));
         listaDeHabitaciones.add(new Habitacion("Suite",2,30,2,80));
         listaDeHabitaciones.add(new Habitacion("Suite",2,30,2,80));
        

       

    }

private void fecha(){
    LocalDate now=LocalDate.now();
    Locale spanishLocale=new Locale("es","ES");
    
    lblFecha.setText(now.format(DateTimeFormatter.ofPattern(""
            + "'Hoy es ' EEEE dd 'de'  MMMM 'del' yyyy",spanishLocale)));

}
  /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlInicio = new javax.swing.JPanel();
        pnlMenu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnClientes = new javax.swing.JButton();
        btnReserva = new javax.swing.JButton();
        btnServicios = new javax.swing.JButton();
        btnPrincipal = new javax.swing.JButton();
        pnlCabecero = new javax.swing.JPanel();
        lblFecha = new javax.swing.JLabel();
        lblMensaje = new javax.swing.JLabel();
        pnlFondo = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ReserHotel");
        setMaximumSize(new java.awt.Dimension(1000, 800));

        pnlInicio.setBackground(new java.awt.Color(255, 255, 255));
        pnlInicio.setMaximumSize(new java.awt.Dimension(1000, 620));
        pnlInicio.setMinimumSize(new java.awt.Dimension(1000, 620));

        pnlMenu.setBackground(new java.awt.Color(13, 71, 161));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("RESERHOTEL");

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator1.setOpaque(true);

        btnClientes.setBackground(new java.awt.Color(21, 101, 192));
        btnClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/cliente_1.png"))); // NOI18N
        btnClientes.setText("Registro de  clientes");
        btnClientes.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        btnClientes.setBorderPainted(false);
        btnClientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClientes.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnClientes.setIconTextGap(10);
        btnClientes.setMaximumSize(new java.awt.Dimension(130, 26));
        btnClientes.setMinimumSize(new java.awt.Dimension(130, 26));
        btnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientesActionPerformed(evt);
            }
        });

        btnReserva.setBackground(new java.awt.Color(21, 101, 192));
        btnReserva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/reserva (1).jpg"))); // NOI18N
        btnReserva.setText("Reserva");
        btnReserva.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        btnReserva.setBorderPainted(false);
        btnReserva.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReserva.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnReserva.setIconTextGap(10);
        btnReserva.setMaximumSize(new java.awt.Dimension(130, 26));
        btnReserva.setMinimumSize(new java.awt.Dimension(130, 26));
        btnReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReservaActionPerformed(evt);
            }
        });

        btnServicios.setBackground(new java.awt.Color(21, 101, 192));
        btnServicios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/servicios.jpeg"))); // NOI18N
        btnServicios.setText("Servicios");
        btnServicios.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        btnServicios.setBorderPainted(false);
        btnServicios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnServicios.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnServicios.setIconTextGap(10);
        btnServicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnServiciosActionPerformed(evt);
            }
        });

        btnPrincipal.setBackground(new java.awt.Color(21, 101, 192));
        btnPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/home-outline.png"))); // NOI18N
        btnPrincipal.setText("Pagina principal");
        btnPrincipal.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        btnPrincipal.setBorderPainted(false);
        btnPrincipal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPrincipal.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnPrincipal.setIconTextGap(10);
        btnPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrincipalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlMenuLayout = new javax.swing.GroupLayout(pnlMenu);
        pnlMenu.setLayout(pnlMenuLayout);
        pnlMenuLayout.setHorizontalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(btnPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnServicios, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        pnlMenuLayout.setVerticalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(btnPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnServicios, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnlCabecero.setBackground(new java.awt.Color(51, 102, 255));
        pnlCabecero.setPreferredSize(new java.awt.Dimension(29860, 100));

        lblFecha.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblFecha.setText("FECHA");

        javax.swing.GroupLayout pnlCabeceroLayout = new javax.swing.GroupLayout(pnlCabecero);
        pnlCabecero.setLayout(pnlCabeceroLayout);
        pnlCabeceroLayout.setHorizontalGroup(
            pnlCabeceroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCabeceroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(219, Short.MAX_VALUE))
        );
        pnlCabeceroLayout.setVerticalGroup(
            pnlCabeceroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCabeceroLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(lblFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        lblMensaje.setBackground(new java.awt.Color(204, 204, 204));
        lblMensaje.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblMensaje.setForeground(new java.awt.Color(0, 153, 153));
        lblMensaje.setText("BIENVENIDO");

        pnlFondo.setBackground(new java.awt.Color(204, 255, 204));
        pnlFondo.setPreferredSize(new java.awt.Dimension(750, 430));

        javax.swing.GroupLayout pnlFondoLayout = new javax.swing.GroupLayout(pnlFondo);
        pnlFondo.setLayout(pnlFondoLayout);
        pnlFondoLayout.setHorizontalGroup(
            pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlFondoLayout.setVerticalGroup(
            pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlInicioLayout = new javax.swing.GroupLayout(pnlInicio);
        pnlInicio.setLayout(pnlInicioLayout);
        pnlInicioLayout.setHorizontalGroup(
            pnlInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInicioLayout.createSequentialGroup()
                .addComponent(pnlMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlInicioLayout.createSequentialGroup()
                        .addComponent(lblMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(pnlCabecero, javax.swing.GroupLayout.DEFAULT_SIZE, 784, Short.MAX_VALUE)
                    .addComponent(pnlFondo, javax.swing.GroupLayout.DEFAULT_SIZE, 784, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlInicioLayout.setVerticalGroup(
            pnlInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInicioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlCabecero, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlFondo, javax.swing.GroupLayout.DEFAULT_SIZE, 525, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(pnlMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnServiciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnServiciosActionPerformed
        // TODO add your handling code here:
        //pnlServicios = new PnlServicios();
        //agregarPanel(pnlServicios);
       pnlServicios2=new PnlServicios2();
       agregarPanel(pnlServicios2);
    }//GEN-LAST:event_btnServiciosActionPerformed

    private void btnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesActionPerformed
        // TODO add your handling code here:
        pnlCliente=new PnlCliente();
        agregarPanel(pnlCliente);
    }//GEN-LAST:event_btnClientesActionPerformed

    private void btnReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReservaActionPerformed
        // TODO add your handling code here:
         /*pnlHabitacion21= new PnlHabitacion21();
         agregarPanel(pnlHabitacion21);*/
        pnlHabitacion21= new PnlHabitacion21();
         agregarPanel(pnlHabitacion21);
    }//GEN-LAST:event_btnReservaActionPerformed

    private void btnPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrincipalActionPerformed
        // TODO add your handling code here:
         pnlPrincipal=new PnlPrincipal();
        agregarPanel(pnlPrincipal);
    }//GEN-LAST:event_btnPrincipalActionPerformed
private void agregarPanel(JPanel pnl){
     pnl.setSize(1000,620);
        pnl.setLocation(0,0);
        pnlFondo.removeAll();
        pnlFondo.add(pnl, BorderLayout.CENTER);
        pnlFondo.revalidate();
        pnlFondo.repaint();    
 
}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaginaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaginaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaginaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaginaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PaginaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClientes;
    private javax.swing.JButton btnPrincipal;
    private javax.swing.JButton btnReserva;
    private javax.swing.JButton btnServicios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblMensaje;
    private javax.swing.JPanel pnlCabecero;
    private javax.swing.JPanel pnlFondo;
    private javax.swing.JPanel pnlInicio;
    private javax.swing.JPanel pnlMenu;
    // End of variables declaration//GEN-END:variables

}

