/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import Modelo.Cliente;
import Modelo.Habitacion;
import Modelo.Reserva;
import Vista.PaginaPrincipal;
import Vista.PaginaPrincipal;
import Vista.PaginaPrincipal;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author usuario
 */
public class PnlFactura_1 extends javax.swing.JPanel {
DefaultTableModel dtmModelo;
 Habitacion c;
 Cliente c1;
 int indiceHabitacionSeleccionada=-1;
 Reserva r;
 private int diasTranscurridos;
    /**
     * Creates new form factra
     */
    public PnlFactura_1() {
        initComponents();
        PnlFondo3.setVisible(false);
                dtmModelo=new DefaultTableModel();
        dtmModelo.addColumn("Tipo de habitacion");
        dtmModelo.addColumn("Piso");
        dtmModelo.addColumn("Numero de habitacion");
        dtmModelo.addColumn("Capacidad");
        dtmModelo.addColumn("Precio");
        
        tblHabitacion21.setModel(dtmModelo);
        for(Cliente r :PaginaPrincipal.listaDeClientes){
            cmbClientes.addItem(r.getNombre() +" "+r.getApellido());  
        }
        for (Habitacion c:PaginaPrincipal.listaDeHabitaciones){
        dtmModelo.addRow(new Object[] {c.getTipoDeHabitacion(),c.getPiso(),c.getNumeroDeHabitacion(),
           c.getCapacidad(),c.getPrecio()});      
        }
        indiceHabitacionSeleccionada=-1;
           
    }
 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgFormaDePago = new javax.swing.ButtonGroup();
        fondo = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        rbtTransferencia = new javax.swing.JRadioButton();
        rbtTarjeta = new javax.swing.JRadioButton();
        jdcFechaIngreso = new com.toedter.calendar.JDateChooser();
        jdcFechaSalida = new com.toedter.calendar.JDateChooser();
        cmbClientes = new javax.swing.JComboBox<>();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblHabitacion21 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDescripccion = new javax.swing.JTextArea();
        PnlFondo3 = new javax.swing.JPanel();
        lblNombreFactura3 = new javax.swing.JLabel();
        lblNombre3 = new javax.swing.JLabel();
        lblFechaIngreso3 = new javax.swing.JLabel();
        lblFechaIngresoFactura3 = new javax.swing.JLabel();
        lblFechaSalida3 = new javax.swing.JLabel();
        lblFechaSalidaFactura3 = new javax.swing.JLabel();
        lblTipoHabitacion3 = new javax.swing.JLabel();
        lblTipoHabitacionFactura3 = new javax.swing.JLabel();
        lblIVA3 = new javax.swing.JLabel();
        lblTotal3 = new javax.swing.JLabel();
        lblIVAFactura3 = new javax.swing.JLabel();
        lblTotalFactura3 = new javax.swing.JLabel();
        lblFormaPago3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblFormaPagoFactura3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblSubTotal = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnFactura = new javax.swing.JButton();
        btnNuevaReserva = new javax.swing.JButton();
        btnCalcuclarReserva = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setText("Fecha ingreso");

        jLabel2.setText("Fecha de salida");

        jLabel3.setText("Cliente");

        jLabel4.setText("Forma de pago");
        jLabel4.setToolTipText("");

        btgFormaDePago.add(rbtTransferencia);
        rbtTransferencia.setText("Transferencia");

        btgFormaDePago.add(rbtTarjeta);
        rbtTarjeta.setText("Tarjeta de credito");

        jdcFechaIngreso.setDateFormatString("dd/MM/yyyy");

        jdcFechaSalida.setDateFormatString("dd/MM/yyyy");

        jScrollPane5.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane5.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        tblHabitacion21.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblHabitacion21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHabitacion21MouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tblHabitacion21);

        txtDescripccion.setColumns(20);
        txtDescripccion.setRows(5);
        txtDescripccion.setBorder(javax.swing.BorderFactory.createTitledBorder("Descripcción de habitación"));
        jScrollPane2.setViewportView(txtDescripccion);

        PnlFondo3.setBackground(new java.awt.Color(255, 255, 255));
        PnlFondo3.setBorder(javax.swing.BorderFactory.createTitledBorder("Factura"));

        lblNombreFactura3.setText("Nombre");

        lblNombre3.setText("jLabel3");

        lblFechaIngreso3.setText("Fecha de Ingreso");

        lblFechaIngresoFactura3.setText("jLabel2");

        lblFechaSalida3.setText("Fecha de Salida");

        lblFechaSalidaFactura3.setText("jLabel4");

        lblTipoHabitacion3.setText("Tipo de Habitación");

        lblTipoHabitacionFactura3.setText("jLabel1");

        lblIVA3.setText("%IVA");

        lblTotal3.setText("Total");

        lblIVAFactura3.setText("jLabel5");

        lblTotalFactura3.setText("jLabel6");

        lblFormaPago3.setText("Forma de Pago");

        lblFormaPagoFactura3.setText("jLabel1");

        jLabel6.setText("SubTotal");

        lblSubTotal.setText("jLabel9");

        javax.swing.GroupLayout PnlFondo3Layout = new javax.swing.GroupLayout(PnlFondo3);
        PnlFondo3.setLayout(PnlFondo3Layout);
        PnlFondo3Layout.setHorizontalGroup(
            PnlFondo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlFondo3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(PnlFondo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PnlFondo3Layout.createSequentialGroup()
                        .addGroup(PnlFondo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTotal3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblIVA3, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PnlFondo3Layout.createSequentialGroup()
                                .addGap(193, 193, 193)
                                .addComponent(jLabel5))
                            .addGroup(PnlFondo3Layout.createSequentialGroup()
                                .addGap(158, 158, 158)
                                .addComponent(lblFormaPagoFactura3, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PnlFondo3Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addGroup(PnlFondo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PnlFondo3Layout.createSequentialGroup()
                                        .addComponent(lblTipoHabitacion3, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblTipoHabitacionFactura3, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lblFormaPago3, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(PnlFondo3Layout.createSequentialGroup()
                        .addGroup(PnlFondo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PnlFondo3Layout.createSequentialGroup()
                                .addGroup(PnlFondo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnlFondo3Layout.createSequentialGroup()
                                        .addComponent(lblFechaSalida3, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnlFondo3Layout.createSequentialGroup()
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(59, 59, 59)))
                                .addGroup(PnlFondo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblFechaSalidaFactura3, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblIVAFactura3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblTotalFactura3, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(PnlFondo3Layout.createSequentialGroup()
                                .addGroup(PnlFondo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblFechaIngreso3, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblNombreFactura3, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(PnlFondo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNombre3, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblFechaIngresoFactura3, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        PnlFondo3Layout.setVerticalGroup(
            PnlFondo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlFondo3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PnlFondo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreFactura3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombre3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PnlFondo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFechaIngreso3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFechaIngresoFactura3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PnlFondo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFechaSalidaFactura3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFechaSalida3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PnlFondo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PnlFondo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIVA3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIVAFactura3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PnlFondo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotal3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTotalFactura3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(111, 111, 111)
                .addGroup(PnlFondo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PnlFondo3Layout.createSequentialGroup()
                        .addGroup(PnlFondo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTipoHabitacion3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTipoHabitacionFactura3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PnlFondo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFormaPago3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFormaPagoFactura3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PnlFondo3Layout.createSequentialGroup()
                        .addGap(232, 232, 232)
                        .addComponent(jLabel5))))
        );

        jLabel9.setText("Elija el tipo de habitación de su preferencia");

        btnFactura.setText("Facturar");
        btnFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFacturaActionPerformed(evt);
            }
        });

        btnNuevaReserva.setText("Nueva Reserva");
        btnNuevaReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevaReservaActionPerformed(evt);
            }
        });

        btnCalcuclarReserva.setText("Calcular Precio");
        btnCalcuclarReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcuclarReservaActionPerformed(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbtTarjeta)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(rbtTransferencia)
                                            .addComponent(jdcFechaSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cmbClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jdcFechaIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 626, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(PnlFondo3, javax.swing.GroupLayout.PREFERRED_SIZE, 318, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(btnGuardar)
                        .addGap(29, 29, 29)
                        .addComponent(btnCalcuclarReserva)
                        .addGap(32, 32, 32)
                        .addComponent(btnNuevaReserva)
                        .addGap(35, 35, 35)
                        .addComponent(btnFactura)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(6, 6, 6))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(PnlFondo3, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cmbClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jdcFechaIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jdcFechaSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, 0)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rbtTransferencia))
                                .addGap(18, 18, 18)
                                .addComponent(rbtTarjeta)
                                .addGap(0, 0, 0)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnGuardar)
                            .addComponent(btnCalcuclarReserva)
                            .addComponent(btnNuevaReserva)
                            .addComponent(btnFactura))
                        .addGap(17, 17, 17))))
        );

        fondo.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, 970, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(fondo, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblHabitacion21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHabitacion21MouseClicked
        // TODO add your handling code here:
        indiceHabitacionSeleccionada=tblHabitacion21.getSelectedRow();
        Habitacion HabitacionSeleccionada=PaginaPrincipal.listaDeHabitaciones.get(indiceHabitacionSeleccionada);
        borrarAreaDeTexto();
        if(HabitacionSeleccionada.getTipoDeHabitacion().equals("Matrimonial")){
            txtDescripccion.append(HabitacionSeleccionada.habitacionDoble()+ "\n");
        }
        if(HabitacionSeleccionada.getTipoDeHabitacion().equals("Triple")){
            txtDescripccion.append(HabitacionSeleccionada.habitacionTriple()+ "\n");
        }
        if(HabitacionSeleccionada.getTipoDeHabitacion().equals("Simple")){
            txtDescripccion.append(HabitacionSeleccionada.habitacionSimple()+ "\n");
        }

        if(HabitacionSeleccionada.getTipoDeHabitacion().equals("Cuadruple")){
            txtDescripccion.append(HabitacionSeleccionada.habitacionCuadruple()+ "\n");
        }
        if(HabitacionSeleccionada.getTipoDeHabitacion().equals("ConnectingRooms")){
            txtDescripccion.append(HabitacionSeleccionada.habitacionConnectingRooms()+ "\n");
        }
        if(HabitacionSeleccionada.getTipoDeHabitacion().equals("Suite")){
            txtDescripccion.append(HabitacionSeleccionada.Suite()+"\n");
        }

    }//GEN-LAST:event_tblHabitacion21MouseClicked

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        guarfarInformacion();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFacturaActionPerformed

        PnlFondo3.setVisible(true);
factura();
    }//GEN-LAST:event_btnFacturaActionPerformed

    private void btnNuevaReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevaReservaActionPerformed

        limpiar();
    }//GEN-LAST:event_btnNuevaReservaActionPerformed

    private void btnCalcuclarReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcuclarReservaActionPerformed

        String tipoHabitacion = ""; // Obtener el tipo de habitación seleccionado
        Habitacion habitacionSeleccionada = PaginaPrincipal.listaDeHabitaciones.get(indiceHabitacionSeleccionada);
        tipoHabitacion = habitacionSeleccionada.getTipoDeHabitacion();
        int diasTranscurridos = this.diasTranscurridos; // Obtener los días transcurridos

        double precioPorNoche = 0.0;
        switch (tipoHabitacion) {
            case "Matrimonial":
            precioPorNoche = 80.0;
            break;
            case "Triple":
            precioPorNoche = 115.0;
            break;
            case "Simple":
            precioPorNoche = 50.0;
            break;
            case "Cuadruple":
            precioPorNoche = 125.0;
            break;
            case "ConnectingRooms":
            precioPorNoche = 150.0;
            break;
            case "Suite":
            precioPorNoche = 180.0;
            break;
            default:
            break;
        }

        double precioTotal = precioPorNoche * diasTranscurridos;
        txtDescripccion.append("\nPrecio total de la reserva: " + precioTotal+ "$");
    }//GEN-LAST:event_btnCalcuclarReservaActionPerformed
private void limpiar () {
    cmbClientes.setSelectedIndex(0);
    jdcFechaIngreso.setCalendar(null);
    jdcFechaSalida.setCalendar(null);
    btgFormaDePago.clearSelection();
    txtDescripccion.setText("");
    }
private void borrarAreaDeTexto(){
        txtDescripccion.setText("");
    }
private void seleccionarHabitacion(){
    if (indiceHabitacionSeleccionada!=-1){
            PaginaPrincipal.listaDeHabitaciones.remove(indiceHabitacionSeleccionada);
            limpiarTablaDeClientes();
            agregarListaCompletaALaTabla();
            indiceHabitacionSeleccionada=-1;
        }
    
}

    private void limpiarTablaDeClientes(){
    for(int i=0;i<tblHabitacion21.getRowCount();i++){
        dtmModelo.removeRow(i);
        i--;//decremento asi o asi; i-=1
    }   
}
    private void agregarListaCompletaALaTabla(){
    for(Habitacion c:PaginaPrincipal.listaDeHabitaciones)
        agregarHabitacionesALaTabla (c);
}
    private void agregarHabitacionesALaTabla(Habitacion h){
    dtmModelo.addRow(new Object[]{h.getTipoDeHabitacion(),h.getPiso(),h.getNumeroDeHabitacion(),
    h.getCapacidad(),h.getPrecio()}); 
}
    
    private void agregarPanel(JPanel pnl){
     pnl.setSize(1000,620);
        pnl.setLocation(0,0);
        fondo.removeAll();
        fondo.add(pnl);
       fondo.revalidate();
        fondo.repaint();    
 
}
    private void guarfarInformacion(){
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss", new Locale("es"));       
        String fechaIngreso = sdf.format(jdcFechaIngreso.getDate());
        String fechaSalida = sdf.format(jdcFechaSalida.getDate());
        Date fecha1 = jdcFechaIngreso.getDate();
        Date fecha2 = jdcFechaSalida.getDate();
        long diffMillis = fecha2.getTime() - fecha1.getTime();
         diasTranscurridos = (int) (diffMillis / 86400000);
        r=new Reserva(fechaIngreso,fechaSalida);
        if(rbtTransferencia.isSelected())
                r.setFormaDePago("Transferencia");
        if(rbtTarjeta.isSelected())
                r.setFormaDePago("Tarjeta de credito");
        txtDescripccion.append("Fecha ingreso: " + r.getFechaIngreso() + "\nFecha salida: " +
         r.getFechaSalida() + "\nForma de pago: " + r.getFormaDePago() + "\n" + "Dias reservados: "+ diasTranscurridos);
    }
public void factura(){
    String cliente=cmbClientes.getSelectedItem().toString();      
       lblNombre3.setText(cliente);
       lblNombre3.setVisible(true);
         SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss", new Locale("es")); 
       String fechaIngreso = sdf.format(jdcFechaIngreso.getDate());
        String fechaSalida = sdf.format(jdcFechaSalida.getDate());
        Date fecha1 = jdcFechaIngreso.getDate();
        Date fecha2 = jdcFechaSalida.getDate();
       lblFechaIngresoFactura3.setText(fechaIngreso);
        
        lblFechaSalidaFactura3.setText( fechaSalida);
       
         indiceHabitacionSeleccionada=tblHabitacion21.getSelectedRow();
        Habitacion HabitacionSeleccionada=PaginaPrincipal.listaDeHabitaciones.get(indiceHabitacionSeleccionada);
        borrarAreaDeTexto();
        if(HabitacionSeleccionada.getTipoDeHabitacion().equals("Matrimonial")){
             lblTipoHabitacionFactura3.setText("Matrrmonial");
            lblTipoHabitacionFactura3.setVisible(true);
        }
        if(HabitacionSeleccionada.getTipoDeHabitacion().equals("Triple")){
             lblTipoHabitacionFactura3.setText("Triple");
            lblTipoHabitacionFactura3.setVisible(true);
        }
        if(HabitacionSeleccionada.getTipoDeHabitacion().equals("Simple")){
             lblTipoHabitacionFactura3.setText("Simple");
            lblTipoHabitacionFactura3.setVisible(true);
        }

        if(HabitacionSeleccionada.getTipoDeHabitacion().equals("Cuadruple")){
             lblTipoHabitacionFactura3.setText("Cuadruple");
            lblTipoHabitacionFactura3.setVisible(true);
        }
        if(HabitacionSeleccionada.getTipoDeHabitacion().equals("ConnectingRooms")){
            lblTipoHabitacionFactura3.setText("ConnectingRooms");
            lblTipoHabitacionFactura3.setVisible(true);
        }
        if(HabitacionSeleccionada.getTipoDeHabitacion().equals("Suite")){
            lblTipoHabitacionFactura3.setText("Suite");
            lblTipoHabitacionFactura3.setVisible(true);
            
        }
        if(rbtTransferencia.isSelected())
                r.setFormaDePago("Transferencia");
        lblFormaPagoFactura3.setVisible(true);
        if(rbtTarjeta.isSelected())
                r.setFormaDePago("Tarjeta de credito");
       
        lblIVAFactura3.setText("0,12");
       
        lblTotalFactura3.setText(""+calcularPrecioTotal());

        lblSubTotal.setText(""+calcuclarSubTotal());
       
}
public double calcuclarSubTotal(){
    String tipoHabitacion = ""; // Obtener el tipo de habitación seleccionado
        Habitacion habitacionSeleccionada = PaginaPrincipal.listaDeHabitaciones.get(indiceHabitacionSeleccionada);
        tipoHabitacion = habitacionSeleccionada.getTipoDeHabitacion();
        int diasTranscurridos = this.diasTranscurridos; // Obtener los días transcurridos

        double precioPorNoche = 0.0;
        switch (tipoHabitacion) {
            case "Matrimonial":
            precioPorNoche = 80.0;
            break;
            case "Triple":
            precioPorNoche = 115.0;
            break;
            case "Simple":
            precioPorNoche = 50.0;
            break;
            case "Cuadruple":
            precioPorNoche = 125.0;
            break;
            case "ConnectingRooms":
            precioPorNoche = 150.0;
            break;
            case "Suite":
            precioPorNoche = 180.0;
            break;
            default:
            break;
        }
        double Total =precioPorNoche * diasTranscurridos;
    return Total;
}
public double calcularPrecioTotal(){
    double iva=0.12;
 double total = calcuclarSubTotal() +(calcuclarSubTotal()*iva);
    return total;
    
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PnlFondo3;
    private javax.swing.ButtonGroup btgFormaDePago;
    private javax.swing.JButton btnCalcuclarReserva;
    private javax.swing.JButton btnFactura;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevaReserva;
    private javax.swing.JComboBox<String> cmbClientes;
    private javax.swing.JScrollPane fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane5;
    private com.toedter.calendar.JDateChooser jdcFechaIngreso;
    private com.toedter.calendar.JDateChooser jdcFechaSalida;
    private javax.swing.JLabel lblFechaIngreso3;
    private javax.swing.JLabel lblFechaIngresoFactura3;
    private javax.swing.JLabel lblFechaSalida3;
    private javax.swing.JLabel lblFechaSalidaFactura3;
    private javax.swing.JLabel lblFormaPago3;
    private javax.swing.JLabel lblFormaPagoFactura3;
    private javax.swing.JLabel lblIVA3;
    private javax.swing.JLabel lblIVAFactura3;
    private javax.swing.JLabel lblNombre3;
    private javax.swing.JLabel lblNombreFactura3;
    private javax.swing.JLabel lblSubTotal;
    private javax.swing.JLabel lblTipoHabitacion3;
    private javax.swing.JLabel lblTipoHabitacionFactura3;
    private javax.swing.JLabel lblTotal3;
    private javax.swing.JLabel lblTotalFactura3;
    private javax.swing.JRadioButton rbtTarjeta;
    private javax.swing.JRadioButton rbtTransferencia;
    private javax.swing.JTable tblHabitacion21;
    private javax.swing.JTextArea txtDescripccion;
    // End of variables declaration//GEN-END:variables
}
